openapi: '3.0.1'
info:
  title: BookClub
  description: An API for managing a small BookClub
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: BookClub Team
    url: https://github.com/joniumGit/PWP-BookClub
  version: 0.1.0
paths:
  /:
    get:
      responses:
        200:
          description: ok

components:
  schemas:
    User:
      type: object
      required:
        - username
        - description
      properties:
        username:
          type: string
          maxLength: 20
          minLength: 1
        description:
          type: string
          nullable: true
          maxLength: 250
    Book:
      type: object
      required:
        - handle
        - name
        - description
      properties:
        handle:
          type: string
          maxLength: 60
        name:
          type: string
          maxLength: 250
        description:
          type: string
          maxLength: 65000
        pages:
          type: integer
    UserBook:
      allOf:
        - $ref: '#/components/schemas/Book'
        - type: object
          required:
            - user
          properties:
            user:
              type: string
            status:
              type: string
              enum: [
                  'pending',
                  'reading',
                  'complete'
              ]
            reviewed:
              type: boolean
            ignored:
              type: boolean
            liked:
              type: boolean
            page:
              type: integer
    Club:
      type: object
      required:
        - handle
      properties:
        handle:
          type: string
          maxLength: 60
          minLength: 1
        description:
          type: string
          maxLength: 2000
        owner:
          type: string
    Review:
      type: object
      required:
        - user
        - book
        - stars

      properties:
        user:
          type: string
        book:
          type: string
        stars:
          type: integer
          minimum: 1
          maximum: 5
          default: 3
        title:
          type: string
        content:
          type: string
          maxLength: 65000
    Comment:
      type: object
      required:
        - id
        - user
        - content
      properties:
        id:
          type: string
          pattern: \d+
        user:
          type: string
        content:
          type: string
          maxLength: 65000
